#!/usr/bin/env ruby

puts "you sunk my battleship"

@my_board = Hash.new
@your_board = Hash.new
@battleships = ["1"]

def create_board () 
	board = Hash.new
	('a'..'j').each do |y| 
		(1..10).each do |x|
			board["#{y}#{x}"] = "X"
		end
	end
	return board
end

def print_board (board)
	('a'..'j').each do |y|
		(1..10).each do |x|
			print board["#{y}#{x}"]
		end
		puts
	end
end


@my_board = create_board()
print_board(@my_board)
@my_board["a3"] = "O"
system("clear")
print_board(@my_board)

