#!/usr/bin/env ruby

require './lib/ship'
require './lib/board'
require './lib/score'


#system("clear")

# create ships 
@bs = Ship.battleship
@bs.coordinates = ["a1", "a2", "a3", "a4"]

@ac = Ship.aircraft_carrier
@ac.coordinates = ["e5", "e6", "e7", "e8", "e9"]

@sub = Ship.submarine
@sub.coordinates = ["b1", "c1", "d1"]

@destroyer = Ship.destroyer
@destroyer.coordinates = ["h3", "i3", "j3"]

@pb = Ship.patrol_boat 
@pb.coordinates = ["c9", "c10"]

@ships = [@bs, @ac, @sub, @destroyer, @pb]


#create and update the computer board with the ships
@computer_board = Board.new
@player1_board = Board.new
@computer_board.create
@player1_board.create

@ships.each do |ship|
	ship.coordinates.each do |c|
		@computer_board.update("#{c}", "B")
	end
end


# create score for player1
@player1_score = Score.new

#play
def check_for_hit (shot)
	@ships.each do |ship|
		ship.coordinates.each do |c|
			if c.eql? shot
				#update the player board with a hit
				puts "Hit on #{ship.ship_name}"
				@player1_board.update("#{shot}", "H")
				@player1_score.hits += 1
				#increment ship hit 
				ship.hit
				if ship.sunk 
					puts "you sunk my #{ship.ship_name}"
					if @player1_score.is_winner
						puts "you sunk all my ships!"
						puts "you win"
						@player1_board.print_it
						exit 0
					end
				end
				return
			end
		end
	end
	#if you made it this far it is a miss
	puts "Miss"
	@player1_board.update("#{shot}", "M")
	@player1_score.misses += 1
end

def main_menu
	puts "What do you want to do?"
	puts "1. play"
	puts "2. see your current score"
	puts "3. see your current board"
	puts "4. quit"
	print "please enter a number: "
end

def main 
	puts "Welcome to Battleship"
	while true
		main_menu
		STDOUT.flush
		answer = gets.chomp
		puts
		case answer
		when "1"
			print "enter a board coordinate (ex a2): "
			STDOUT.flush
			c = gets.chomp
			check_for_hit("#{c}") 
			puts
		when "2"
			puts "Misses #{@player1_score.misses} Hits #{@player1_score.hits}"
			puts
		when "3"
			@player1_board.print_it
			puts
		when "4"
			puts "Thanks for playing"
			exit 0
		else
			puts "invalid option"
		end
	end
end

main
